/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package model.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class TrajSegmentAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1679073373140949655L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TrajSegmentAvro\",\"namespace\":\"model.avro\",\"fields\":[{\"name\":\"points\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"TrajPointAvro\",\"fields\":[{\"name\":\"taxiId\",\"type\":\"string\"},{\"name\":\"time\",\"type\":\"string\"},{\"name\":\"lon\",\"type\":\"double\"},{\"name\":\"lat\",\"type\":\"double\"},{\"name\":\"direction\",\"type\":\"double\"},{\"name\":\"speed\",\"type\":\"double\"},{\"name\":\"passenger\",\"type\":\"int\"},{\"name\":\"utc\",\"type\":\"long\"},{\"name\":\"cellID\",\"type\":\"string\"}]}}},{\"name\":\"code\",\"type\":\"string\"},{\"name\":\"taxiID\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<TrajSegmentAvro> ENCODER =
      new BinaryMessageEncoder<TrajSegmentAvro>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TrajSegmentAvro> DECODER =
      new BinaryMessageDecoder<TrajSegmentAvro>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<TrajSegmentAvro> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<TrajSegmentAvro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<TrajSegmentAvro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<TrajSegmentAvro>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this TrajSegmentAvro to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a TrajSegmentAvro from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a TrajSegmentAvro instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static TrajSegmentAvro fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.util.List<model.avro.TrajPointAvro> points;
  @Deprecated public java.lang.CharSequence code;
  @Deprecated public java.lang.CharSequence taxiID;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TrajSegmentAvro() {}

  /**
   * All-args constructor.
   * @param points The new value for points
   * @param code The new value for code
   * @param taxiID The new value for taxiID
   */
  public TrajSegmentAvro(java.util.List<model.avro.TrajPointAvro> points, java.lang.CharSequence code, java.lang.CharSequence taxiID) {
    this.points = points;
    this.code = code;
    this.taxiID = taxiID;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return points;
    case 1: return code;
    case 2: return taxiID;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: points = (java.util.List<model.avro.TrajPointAvro>)value$; break;
    case 1: code = (java.lang.CharSequence)value$; break;
    case 2: taxiID = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'points' field.
   * @return The value of the 'points' field.
   */
  public java.util.List<model.avro.TrajPointAvro> getPoints() {
    return points;
  }


  /**
   * Sets the value of the 'points' field.
   * @param value the value to set.
   */
  public void setPoints(java.util.List<model.avro.TrajPointAvro> value) {
    this.points = value;
  }

  /**
   * Gets the value of the 'code' field.
   * @return The value of the 'code' field.
   */
  public java.lang.CharSequence getCode() {
    return code;
  }


  /**
   * Sets the value of the 'code' field.
   * @param value the value to set.
   */
  public void setCode(java.lang.CharSequence value) {
    this.code = value;
  }

  /**
   * Gets the value of the 'taxiID' field.
   * @return The value of the 'taxiID' field.
   */
  public java.lang.CharSequence getTaxiID() {
    return taxiID;
  }


  /**
   * Sets the value of the 'taxiID' field.
   * @param value the value to set.
   */
  public void setTaxiID(java.lang.CharSequence value) {
    this.taxiID = value;
  }

  /**
   * Creates a new TrajSegmentAvro RecordBuilder.
   * @return A new TrajSegmentAvro RecordBuilder
   */
  public static model.avro.TrajSegmentAvro.Builder newBuilder() {
    return new model.avro.TrajSegmentAvro.Builder();
  }

  /**
   * Creates a new TrajSegmentAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TrajSegmentAvro RecordBuilder
   */
  public static model.avro.TrajSegmentAvro.Builder newBuilder(model.avro.TrajSegmentAvro.Builder other) {
    if (other == null) {
      return new model.avro.TrajSegmentAvro.Builder();
    } else {
      return new model.avro.TrajSegmentAvro.Builder(other);
    }
  }

  /**
   * Creates a new TrajSegmentAvro RecordBuilder by copying an existing TrajSegmentAvro instance.
   * @param other The existing instance to copy.
   * @return A new TrajSegmentAvro RecordBuilder
   */
  public static model.avro.TrajSegmentAvro.Builder newBuilder(model.avro.TrajSegmentAvro other) {
    if (other == null) {
      return new model.avro.TrajSegmentAvro.Builder();
    } else {
      return new model.avro.TrajSegmentAvro.Builder(other);
    }
  }

  /**
   * RecordBuilder for TrajSegmentAvro instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TrajSegmentAvro>
    implements org.apache.avro.data.RecordBuilder<TrajSegmentAvro> {

    private java.util.List<model.avro.TrajPointAvro> points;
    private java.lang.CharSequence code;
    private java.lang.CharSequence taxiID;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(model.avro.TrajSegmentAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.points)) {
        this.points = data().deepCopy(fields()[0].schema(), other.points);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.code)) {
        this.code = data().deepCopy(fields()[1].schema(), other.code);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.taxiID)) {
        this.taxiID = data().deepCopy(fields()[2].schema(), other.taxiID);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing TrajSegmentAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(model.avro.TrajSegmentAvro other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.points)) {
        this.points = data().deepCopy(fields()[0].schema(), other.points);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.code)) {
        this.code = data().deepCopy(fields()[1].schema(), other.code);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.taxiID)) {
        this.taxiID = data().deepCopy(fields()[2].schema(), other.taxiID);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'points' field.
      * @return The value.
      */
    public java.util.List<model.avro.TrajPointAvro> getPoints() {
      return points;
    }


    /**
      * Sets the value of the 'points' field.
      * @param value The value of 'points'.
      * @return This builder.
      */
    public model.avro.TrajSegmentAvro.Builder setPoints(java.util.List<model.avro.TrajPointAvro> value) {
      validate(fields()[0], value);
      this.points = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'points' field has been set.
      * @return True if the 'points' field has been set, false otherwise.
      */
    public boolean hasPoints() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'points' field.
      * @return This builder.
      */
    public model.avro.TrajSegmentAvro.Builder clearPoints() {
      points = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'code' field.
      * @return The value.
      */
    public java.lang.CharSequence getCode() {
      return code;
    }


    /**
      * Sets the value of the 'code' field.
      * @param value The value of 'code'.
      * @return This builder.
      */
    public model.avro.TrajSegmentAvro.Builder setCode(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.code = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'code' field has been set.
      * @return True if the 'code' field has been set, false otherwise.
      */
    public boolean hasCode() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'code' field.
      * @return This builder.
      */
    public model.avro.TrajSegmentAvro.Builder clearCode() {
      code = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'taxiID' field.
      * @return The value.
      */
    public java.lang.CharSequence getTaxiID() {
      return taxiID;
    }


    /**
      * Sets the value of the 'taxiID' field.
      * @param value The value of 'taxiID'.
      * @return This builder.
      */
    public model.avro.TrajSegmentAvro.Builder setTaxiID(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.taxiID = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'taxiID' field has been set.
      * @return True if the 'taxiID' field has been set, false otherwise.
      */
    public boolean hasTaxiID() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'taxiID' field.
      * @return This builder.
      */
    public model.avro.TrajSegmentAvro.Builder clearTaxiID() {
      taxiID = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TrajSegmentAvro build() {
      try {
        TrajSegmentAvro record = new TrajSegmentAvro();
        record.points = fieldSetFlags()[0] ? this.points : (java.util.List<model.avro.TrajPointAvro>) defaultValue(fields()[0]);
        record.code = fieldSetFlags()[1] ? this.code : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.taxiID = fieldSetFlags()[2] ? this.taxiID : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TrajSegmentAvro>
    WRITER$ = (org.apache.avro.io.DatumWriter<TrajSegmentAvro>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TrajSegmentAvro>
    READER$ = (org.apache.avro.io.DatumReader<TrajSegmentAvro>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    long size0 = this.points.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (model.avro.TrajPointAvro e0: this.points) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

    out.writeString(this.code);

    out.writeString(this.taxiID);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      long size0 = in.readArrayStart();
      java.util.List<model.avro.TrajPointAvro> a0 = this.points;
      if (a0 == null) {
        a0 = new SpecificData.Array<model.avro.TrajPointAvro>((int)size0, SCHEMA$.getField("points").schema());
        this.points = a0;
      } else a0.clear();
      SpecificData.Array<model.avro.TrajPointAvro> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<model.avro.TrajPointAvro>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          model.avro.TrajPointAvro e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new model.avro.TrajPointAvro();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

      this.code = in.readString(this.code instanceof Utf8 ? (Utf8)this.code : null);

      this.taxiID = in.readString(this.taxiID instanceof Utf8 ? (Utf8)this.taxiID : null);

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          long size0 = in.readArrayStart();
          java.util.List<model.avro.TrajPointAvro> a0 = this.points;
          if (a0 == null) {
            a0 = new SpecificData.Array<model.avro.TrajPointAvro>((int)size0, SCHEMA$.getField("points").schema());
            this.points = a0;
          } else a0.clear();
          SpecificData.Array<model.avro.TrajPointAvro> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<model.avro.TrajPointAvro>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              model.avro.TrajPointAvro e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new model.avro.TrajPointAvro();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        case 1:
          this.code = in.readString(this.code instanceof Utf8 ? (Utf8)this.code : null);
          break;

        case 2:
          this.taxiID = in.readString(this.taxiID instanceof Utf8 ? (Utf8)this.taxiID : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










